### ISSUE TITLE
Questions regarding the rules

### ISSUE THREAD

**Issue by fkye** [RSE-Cambridge/ISC17-SCC-miniDFT#2]
1. Is the report submitted by June 16th public shared?
2. Which version is evaluation 'B' based on? The version by June 16th or the final one at the end of the competition?
3. Could we use a faster version in the reproducibility test? If so, which version is evaluation 'C' based on?

Thanks!

**Comment by fspiga** [comment]
Hello Fkye,

1. The report is not going to be public
2. The "final version", the one you will use during the competition. It can be exactly the same of the one made public or you can do further modification / tuning during the competition itself. The judges will inspect as well the last-minute changes
3. the "pe-23.LOCAL.in" reference tests that is going to use for the reproducibility test runs for 10 minutes on 256 MPI (SandyBridge cores). We cannot make it faster than that, the test has to be reasonable. However the expectation is that you will be able to show reproducibility on that result in the minimum time possible since you had the opportunity before the competition to run it multiple times

We are going to repeat and clarify all these points to all teams via a private email to all group leaders.

-- Filippo
